### ISSUE TITLE
Ошибка при получении исторических свечей

### ISSUE THREAD

**Issue by 60M6ER** [galimru/tinkoff-invest-api#1]
Наткнулся на ошибку при получении исторический свечей.
QueryConverterFactory нужно поменять шаблон даты. hh на HH. Тинькофф принимает в 24 часовом формате. 
Спасибо за клиент. сильно помог. СДК от тинькоффа багованное(

**Comment by galimru** [comment]
Рад слышать что клиент кому-то помогает 😌.

Спасибо за репорт, время поправлю в следующем минорном релизе v1.1.4

Хочу пердупредить, что клиент написал пару дней назад и в продакшене еще не использовал.
Поэтому буду рад любым фидбэкам и баг репортам.

**Comment by 60M6ER** [comment]
Я пока на вчерашней 1.0.0
Из проблем было вот это получение свечей. И то что ордербук приходит без детализации по аск/бид.
Сегодня стрим у Вас появился. Вот думаю начать пробовать его. А то у тинькоффа стримы валятся периодически.
А у Вас в стримах на одну подписку одно соединение получается?

**Comment by galimru** [comment]
Да, стримы только сегодня доделал.
На одном соединение должно работать несколько подписок, но я не проверял этот кейс. 

И пока не тестировал как оно себе ведет в случае плохого соединения.
Подозреваю что надо добавить возможность реконнекта и повторной подписки на события.

**Comment by galimru** [comment]
Несколько подписок на одном соединении работает.
Добавил тест https://github.com/galimru/tinkoff-invest-api/blob/96361e405da111fc06e6dffd89b1112fcc3cc36a/src/test/java/com/github/galimru/tinkoff/StreamingServiceTest.java#L92
